name: Register APP

on:
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Setup python and poetry
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Pull upstream
        run: bash wrapper.sh pull "sync"

      - name: Install requirements
        run: |
          poetry install
          cd register
          npm install

      - name: Register app
        env:
          USER: ${{ secrets.USER }}
          PASSWD: ${{ secrets.PASSWD }}
        run: bash wrapper.sh register

      - name: Commit and push
        run: bash wrapper.sh push "generate app config"
        
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
         retain_days: 1
         keep_minimum_runs: 3
