name: Invoke API

on:
  schedule:
    - cron: '50 */6 * * *'
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Setup python and poetry
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2

      - name: Pull upstream
        run: bash wrapper.sh pull "sync"

      - name: Install requirements
        run: poetry install

      - name: Test Api
        env:
          PASSWD: ${{ secrets.PASSWD }}
        run: bash wrapper.sh invoke

      - name: Commit and push
        run: bash wrapper.sh push "update app config"
      
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
         retain_days: 1
         keep_minimum_runs: 3
