name: Invoke API

on:
  schedule:
    - cron: '55 */6 * * *'
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Setup Python And Poetry
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2

      - name: Pull Upstream
        run: bash wrapper.sh pull "sync"

      - name: Install Requirements
        run: poetry install

      - name: Test Api
        env:
          PASSWD: ${{ secrets.PASSWD }}
        run: bash wrapper.sh invoke
          
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
         retain_days: 1
         keep_minimum_runs: 1

      - name: Commit And Push
        run: bash wrapper.sh push "update app config"
